# -*- coding: utf-8 -*-
"""Test Hate Speech Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GnjX0XVAqSdvnnWZXEEoAJz03x3PGtdd
"""

import joblib
import numpy as np

clf = joblib.load("/content/hate_speech_model.h5")
cv = joblib.load("/content/count_vectorizer.pkl")

def predict(text):
    transformed_text = cv.transform([text]).toarray()
    prediction = clf.predict(transformed_text)
    return prediction[0]

test_data = "I will kill you"
print(predict(test_data))

test_data = "you are awesome"
print(predict(test_data))

test_data = "you are bad i don't like you"
print(predict(test_data))